// Vendors the two remote assets the interface would otherwise pull from Google:
// the webfonts and the icon set. Both end up committed, so the console works with
// no network at all. A dashboard that renders unstyled when the wifi drops is not
// a dashboard you can run a recall from.
//
// Fonts: Manrope, Work Sans, Petrona and JetBrains Mono, all SIL Open Font License.
// Icons: Material Symbols, Apache License 2.0.
//
// Run with `npm run assets`. Output is committed; this is not part of the build.
import fs from "node:fs";
import path from "node:path";
import { ROOT } from "./lib/chain.js";

const FONT_QUERY =
  "family=Petrona:ital,wght@0,400;0,500;0,600;1,400" +
  "&family=Manrope:wght@400;500;600;700" +
  "&family=Work+Sans:wght@400;500;600" +
  "&family=JetBrains+Mono:wght@400;500" +
  "&display=swap";

// Asking as a modern browser gets woff2 rather than the legacy formats.
const BROWSER_UA =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36";

// Latin coverage only. None of these families ship Devanagari, so Hindi falls
// through to the reader's system font either way, and pulling every subset would
// quadruple the payload for glyphs nothing here renders.
const WANTED_SUBSETS = ["latin", "latin-ext"];

const ICONS = [
  "agriculture", "arrow_back", "arrow_forward", "badge", "call_split", "check_circle", "close",
  "download", "edit", "error", "fact_check", "flag", "info", "inventory_2", "local_shipping",
  "location_on", "lock", "logout", "mail", "notifications", "person", "phone_iphone", "pin_drop",
  "print", "qr_code_2", "science", "search", "sell", "shield", "storefront", "summarize",
  "swap_horiz", "thermostat", "translate", "verified", "visibility", "visibility_off", "warning"
];

const FONT_DIR = path.join(ROOT, "web", "fonts");
const CSS_OUT = path.join(ROOT, "web", "css", "fonts.css");
const ICON_OUT = path.join(ROOT, "web", "js", "icons.js");

async function buildFonts() {
  const res = await fetch(`https://fonts.googleapis.com/css2?${FONT_QUERY}`, { headers: { "User-Agent": BROWSER_UA } });
  if (!res.ok) throw new Error(`font stylesheet: ${res.status} ${res.statusText}`);
  const css = await res.text();

  fs.mkdirSync(FONT_DIR, { recursive: true });
  for (const file of fs.readdirSync(FONT_DIR)) fs.unlinkSync(path.join(FONT_DIR, file));

  // Google emits a `/* subset */` comment immediately before each @font-face, so
  // walk comments and blocks together in document order rather than trying to
  // look backwards from a block to the comment that labels it.
  const tokens = [...css.matchAll(/\/\*\s*([a-z0-9-]+)\s*\*\/|@font-face\s*\{([^}]*)\}/g)];
  const kept = [];
  let subset = "latin";
  let bytes = 0;

  for (const token of tokens) {
    if (token[1]) {
      subset = token[1];
      continue;
    }
    const block = token[2];
    if (!WANTED_SUBSETS.includes(subset)) continue;

    const family = /font-family: '([^']+)'/.exec(block)?.[1];
    const weight = /font-weight: (\d+)/.exec(block)?.[1] ?? "400";
    const style = /font-style: (\w+)/.exec(block)?.[1] ?? "normal";
    const url = /url\((https:[^)]+\.woff2)\)/.exec(block)?.[1];
    const range = /unicode-range: ([^;]+);/.exec(block)?.[1];
    if (!family || !url) continue;

    const slug = `${family.toLowerCase().replace(/\s+/g, "-")}-${weight}${style === "italic" ? "-italic" : ""}-${subset}.woff2`;
    const data = Buffer.from(await (await fetch(url)).arrayBuffer());
    fs.writeFileSync(path.join(FONT_DIR, slug), data);
    bytes += data.length;

    kept.push(
      [
        "@font-face {",
        `  font-family: '${family}';`,
        `  font-style: ${style};`,
        `  font-weight: ${weight};`,
        "  font-display: swap;",
        `  src: url('/fonts/${slug}') format('woff2');`,
        range ? `  unicode-range: ${range};` : null,
        "}"
      ]
        .filter(Boolean)
        .join("\n")
    );
  }

  const header = [
    "/* Generated by scripts/build-assets.js. Do not edit by hand.",
    " *",
    " * Manrope, Work Sans, Petrona and JetBrains Mono, served locally under the",
    " * SIL Open Font License 1.1. Self-hosted so the interface never depends on a",
    " * third party being reachable.",
    " */",
    ""
  ].join("\n");

  fs.writeFileSync(CSS_OUT, `${header}${kept.join("\n\n")}\n`);
  console.log(`fonts      ${kept.length} faces, ${(bytes / 1024).toFixed(0)} KB`);
}

async function buildIcons() {
  const entries = [];
  const missing = [];

  for (const name of ICONS) {
    const url = `https://raw.githubusercontent.com/google/material-design-icons/master/symbols/web/${name}/materialsymbolsoutlined/${name}_24px.svg`;
    const res = await fetch(url);
    if (!res.ok) {
      missing.push(name);
      continue;
    }
    const svg = await res.text();
    const paths = [...svg.matchAll(/<path d="([^"]+)"/g)].map((m) => m[1]);
    if (!paths.length) {
      missing.push(name);
      continue;
    }
    entries.push(`  "${name}": ${JSON.stringify(paths.join(" "))}`);
  }

  if (missing.length) throw new Error(`no glyph for: ${missing.join(", ")}`);

  const body = `// Generated by scripts/build-assets.js. Do not edit by hand.
//
// Material Symbols outlined, Apache License 2.0, inlined as path data. Shipping
// paths rather than the icon font means a page with no network shows icons, not
// the literal word "notifications" in forty places.
//
// The viewBox is Material's own 0 -960 960 960.

export const ICON_PATHS = {
${entries.join(",\n")}
};

/** An icon as an inline SVG string, sized in pixels and inheriting text colour. */
export function icon(name, { size = 20, className = "" } = {}) {
  const d = ICON_PATHS[name];
  if (!d) return "";
  return (
    \`<svg viewBox="0 -960 960 960" width="\${size}" height="\${size}" fill="currentColor" \` +
    \`class="\${className}" aria-hidden="true" focusable="false"><path d="\${d}"/></svg>\`
  );
}
`;

  fs.writeFileSync(ICON_OUT, body);
  console.log(`icons      ${entries.length} glyphs, ${(fs.statSync(ICON_OUT).size / 1024).toFixed(1)} KB`);
}

async function main() {
  fs.mkdirSync(path.dirname(CSS_OUT), { recursive: true });
  await buildFonts();
  await buildIcons();
  console.log("assets vendored; nothing in the interface now loads from a third party");
}

main().catch((err) => {
  console.error(`asset build failed: ${err.message}`);
  process.exit(1);
});
