// Regenerates web/js/basemap.js from Natural Earth.
//
// Source: Natural Earth 1:110m Admin 0 Countries, public domain.
// https://www.naturalearthdata.com/
//
// The map layer has to work with no network and no tile server, so the outlines
// are simplified once here and shipped as a module rather than fetched at run
// time. Run this only when the basemap needs regenerating; the output is committed.
import fs from "node:fs";
import path from "node:path";
import { ROOT } from "./lib/chain.js";

const SOURCE =
  "https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_110m_admin_0_countries.geojson";

// India is where every map in this app is actually looked at closely, so it is
// pulled from the 1:50m set at a much tighter tolerance than the rest of the
// world, which only ever appears as coastline context.
const DETAIL_SOURCE =
  "https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_50m_admin_0_countries.geojson";
const DETAIL_ADMIN = "India";
const DETAIL_TOLERANCE = 0.03;

const TOLERANCE = 0.35; // degrees; coarse enough for a country-scale view
const MIN_POINTS = 5; // drop specks that would render as a single pixel
const PRECISION = 2;

/** Perpendicular distance from a point to the segment ab, in degrees. */
function distanceToSegment(p, a, b) {
  let x = a[0];
  let y = a[1];
  let dx = b[0] - x;
  let dy = b[1] - y;

  if (dx !== 0 || dy !== 0) {
    const t = ((p[0] - x) * dx + (p[1] - y) * dy) / (dx * dx + dy * dy);
    if (t > 1) {
      x = b[0];
      y = b[1];
    } else if (t > 0) {
      x += dx * t;
      y += dy * t;
    }
  }
  dx = p[0] - x;
  dy = p[1] - y;
  return Math.sqrt(dx * dx + dy * dy);
}

/** Ramer-Douglas-Peucker, iterative so a long coastline cannot blow the stack. */
function simplify(points, tolerance) {
  if (points.length <= 2) return points;

  const keep = new Uint8Array(points.length);
  keep[0] = 1;
  keep[points.length - 1] = 1;
  const stack = [[0, points.length - 1]];

  while (stack.length) {
    const [first, last] = stack.pop();
    let index = -1;
    let furthest = tolerance;

    for (let i = first + 1; i < last; i++) {
      const d = distanceToSegment(points[i], points[first], points[last]);
      if (d > furthest) {
        furthest = d;
        index = i;
      }
    }

    if (index !== -1) {
      keep[index] = 1;
      stack.push([first, index], [index, last]);
    }
  }

  return points.filter((_, i) => keep[i]);
}

function round(value) {
  return Number(value.toFixed(PRECISION));
}

function ringsFrom(collection, tolerance, filter) {
  const rings = [];
  let sourcePoints = 0;

  for (const feature of collection.features) {
    if (filter && !filter(feature)) continue;
    const geometry = feature.geometry;
    if (!geometry) continue;
    const polygons = geometry.type === "Polygon" ? [geometry.coordinates] : geometry.coordinates;

    for (const polygon of polygons) {
      // Outer ring only. Holes are lakes and enclaves, invisible at this scale.
      const outer = polygon[0];
      sourcePoints += outer.length;
      const reduced = simplify(outer, tolerance);
      if (reduced.length < MIN_POINTS) continue;
      rings.push(reduced.flatMap(([lon, lat]) => [round(lon), round(lat)]));
    }
  }

  return { rings, sourcePoints };
}

async function main() {
  console.log(`fetching ${SOURCE}`);
  const res = await fetch(SOURCE);
  if (!res.ok) throw new Error(`fetch failed: ${res.status} ${res.statusText}`);
  const collection = await res.json();

  const { rings, sourcePoints: basePoints } = ringsFrom(collection, TOLERANCE, (f) => f.properties.ADMIN !== DETAIL_ADMIN);

  console.log(`fetching ${DETAIL_SOURCE}`);
  const detailRes = await fetch(DETAIL_SOURCE);
  if (!detailRes.ok) throw new Error(`fetch failed: ${detailRes.status} ${detailRes.statusText}`);
  const detailCollection = await detailRes.json();

  const detail = ringsFrom(detailCollection, DETAIL_TOLERANCE, (f) => f.properties.ADMIN === DETAIL_ADMIN);
  rings.push(...detail.rings);
  const sourcePoints = basePoints + detail.sourcePoints;

  const total = rings.reduce((n, ring) => n + ring.length / 2, 0);
  const body = `// Generated by scripts/build-basemap.js. Do not edit by hand.
//
// Natural Earth 1:110m Admin 0 Countries, simplified to ${TOLERANCE} degrees and
// rounded to ${PRECISION} decimal places. Natural Earth is in the public domain.
// https://www.naturalearthdata.com/
//
// Each entry is one outer ring, flattened as [lon, lat, lon, lat, ...].

export const OUTLINES = ${JSON.stringify(rings)};
`;

  const out = path.join(ROOT, "web", "js", "basemap.js");
  fs.writeFileSync(out, body);

  console.log(`rings      ${rings.length}`);
  console.log(`points     ${sourcePoints} in, ${total} out (${((total / sourcePoints) * 100).toFixed(1)}%)`);
  console.log(`wrote      ${out}, ${(fs.statSync(out).size / 1024).toFixed(1)} KB`);
}

main().catch((err) => {
  console.error(`basemap build failed: ${err.message}`);
  process.exit(1);
});
